# Generated by Django 4.1.3 on 2023-02-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annualdeclaration", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DateTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_date", models.DateField()),
            ],
        ),
    ]
