# Generated by Django 4.1.3 on 2023-02-27 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("annualdeclaration", "0005_datetest_actions_and_communications_1_and_more"),
    ]

    operations = [
        migrations.RenameModel(old_name="DateTest", new_name="OLD_AnnualDeclaration",),
    ]
