# Generated by Django 4.1.3 on 2022-11-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_firm_user_firm_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="firm",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="user_role",
            field=models.CharField(
                choices=[
                    ("staff", "Staff"),
                    ("reviewer", "Reviewer"),
                    ("ult_resp", "Ultimate responsibility"),
                ],
                default="staff",
                max_length=20,
            ),
        ),
    ]
