# Generated by Django 4.1.3 on 2022-11-30 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="firm_name",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.firm",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="user_role",
            field=models.CharField(
                choices=[
                    ("staff", "Staff"),
                    ("reviewer", "Reviewer"),
                    ("ult_resp", "Ultimate responsibility"),
                    ("admin", "Nexia Enhance administrator"),
                    ("IT_admin", "IT administrator"),
                ],
                default="staff",
                max_length=20,
            ),
        ),
    ]
