# Generated by Django 4.1.3 on 2022-11-30 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_firm_name_user_user_role"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="firm_name",),
        migrations.RemoveField(model_name="user", name="user_role",),
    ]
