# Generated by Django 4.1.3 on 2022-12-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_remove_user_user_role_userattributes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userattributes",
            name="user_role",
            field=models.CharField(
                choices=[
                    ("staff", "Staff"),
                    ("reviewer", "Reviewer"),
                    ("ult_resp", "Ultimate responsibility"),
                    ("admin", "Nexia Enhance administrator"),
                    ("IT_admin", "IT administrator"),
                    ("nexia_user", "Nexia user"),
                    ("nexia_superuser", "Nexia superuser"),
                ],
                default="staff",
                max_length=20,
            ),
        ),
    ]
