# Generated by Django 4.1.3 on 2022-12-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_userattributes_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="userattributes",
            name="is_nexia_reviewer",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userattributes",
            name="is_nexia_superuser",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userattributes",
            name="is_preparer",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userattributes",
            name="is_reviewer",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userattributes",
            name="is_ult_authority",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userattributes",
            name="is_user_manager",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userattributes",
            name="is_viewer",
            field=models.BooleanField(default=False),
        ),
    ]
