# Generated by Django 4.1.3 on 2023-01-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RiskRegister",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quality_objective_category", models.CharField(max_length=500)),
                ("quality_objective", models.TextField(max_length=5000)),
                ("quality_risk", models.TextField(max_length=10000)),
                (
                    "quality_risk_mandatory",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")], max_length=256
                    ),
                ),
                (
                    "quality_risk_firm_size",
                    models.CharField(
                        choices=[
                            ("Small", "Small"),
                            ("Large", "Large"),
                            ("All", "All"),
                        ],
                        max_length=256,
                    ),
                ),
                ("owner", models.CharField(blank=True, max_length=256, null=True)),
                ("risk_response", models.TextField(max_length=100000)),
                (
                    "response_mandatory",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")], max_length=256
                    ),
                ),
                (
                    "risk_response_firm_size",
                    models.CharField(
                        choices=[
                            ("Small", "Small"),
                            ("Large", "Large"),
                            ("All", "All"),
                        ],
                        max_length=256,
                    ),
                ),
                (
                    "response_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", ""),
                            ("Off-the-shelf software", "Off-the-shelf software"),
                            ("In-house software", "In-house software"),
                            ("Certificates", "Certificates"),
                            ("Documented policy", "Documented policy"),
                            ("Documented procedure", "Documented procedure"),
                            ("Other", "Other"),
                        ],
                        max_length=256,
                        null=True,
                    ),
                ),
                (
                    "risk_response_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Risk library", "Risk library"),
                            ("Custom entry", "Custom entry"),
                            (
                                "Custom objective, risks and response",
                                "Custom objective, risks and response",
                            ),
                            ("Custom risks and response", "Custom risks and response"),
                            ("Custom response", "Custom response"),
                        ],
                        default="risk_library",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "response_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", ""),
                            ("In place", "In place"),
                            ("in_progress", "In progress"),
                            ("not_started", "Not started"),
                        ],
                        max_length=150,
                        null=True,
                    ),
                ),
                ("comments", models.TextField(blank=True, max_length=10000, null=True)),
                (
                    "frequency_of_review",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", ""),
                            ("Weekly", "Weekly"),
                            ("Monthly", "Monthly"),
                            ("Quarterly", "Quarterly"),
                            ("Annually", "Annually"),
                        ],
                        max_length=256,
                        null=True,
                    ),
                ),
                ("created_by", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "sign_off_owner",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "sign_off_reviewer",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "upload_files",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
            ],
        ),
    ]
