# Generated by Django 4.1.3 on 2023-01-10 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_alter_userattributes_user_role"),
        ("riskreg", "0001_initial"),
    ]

    operations = [
        # migrations.AddField(
        #     model_name="riskregister",
        #     name="entry_id",
        #     field=models.AutoField(default=1, primary_key=True, serialize=False),
        #     preserve_default=False,
        # ),
        migrations.AddField(
            model_name="riskregister",
            name="entry_type",
            field=models.CharField(
                choices=[
                    ("rd_entry", "rd_entry"),
                    ("custom_rr", "custom_rr"),
                    ("custom_r_rr", "custom_r_rr"),
                    ("custom_o_r_rr", "custom_o_r_rr"),
                    ("custom_c_o_r_rr", "custom_c_o_r_rr"),
                ],
                default=1,
                max_length=256,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="riskregister",
            name="firm_name",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="risk_register_2_entry",
                to="accounts.firm",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="riskregister",
            name="rd_risk_response_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name="riskregister",
            unique_together={("firm_name", "quality_objective_category")},
        ),
        migrations.RemoveField(model_name="riskregister", name="id",),
        migrations.RemoveField(
            model_name="riskregister", name="quality_risk_mandatory",
        ),
        migrations.RemoveField(model_name="riskregister", name="upload_files",),
    ]
