# Generated by Django 4.1.3 on 2023-01-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("riskreg", "0002_riskregister_entry_id_riskregister_entry_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="riskregister",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=2,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
    ]
