# Generated by Django 4.1.3 on 2023-01-20 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("riskreg", "0003_riskregister_id"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="riskregister", unique_together=set(),),
    ]
