# Generated by Django 4.1.3 on 2023-01-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("riskreg", "0006_alter_rca_is_pervasive_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rca",
            name="contributory_cause_1_reviewer_comments",
            field=models.TextField(
                blank=True, null=True, verbose_name="Reviewer comments"
            ),
        ),
        migrations.AlterField(
            model_name="rca",
            name="contributory_cause_2_reviewer_comments",
            field=models.TextField(
                blank=True, null=True, verbose_name="Reviewer comments"
            ),
        ),
        migrations.AlterField(
            model_name="rca",
            name="contributory_cause_3_reviewer_comments",
            field=models.TextField(
                blank=True, null=True, verbose_name="Reviewer comments"
            ),
        ),
        migrations.AlterField(
            model_name="rca",
            name="immediate_cause",
            field=models.TextField(verbose_name="Immediate cause"),
        ),
        migrations.AlterField(
            model_name="rca",
            name="immediate_cause_reviewer_comments",
            field=models.TextField(
                blank=True, null=True, verbose_name="Reviewer comments"
            ),
        ),
        migrations.AlterField(
            model_name="rca",
            name="is_pervasive_comments",
            field=models.TextField(verbose_name="Comments"),
        ),
        migrations.AlterField(
            model_name="rca",
            name="is_severe",
            field=models.BooleanField(
                default=False, verbose_name="Is the deficiency severe?"
            ),
        ),
        migrations.AlterField(
            model_name="rca",
            name="is_severe_comments",
            field=models.TextField(verbose_name="Comments"),
        ),
        migrations.AlterField(
            model_name="rca",
            name="proposed_remedial_action_reviewer_comments",
            field=models.TextField(
                blank=True, null=True, verbose_name="Reviewer comments"
            ),
        ),
        migrations.AlterField(
            model_name="rca",
            name="remedial_action_change",
            field=models.TextField(
                verbose_name="What has changed as a result of the remedial action?"
            ),
        ),
        migrations.AlterField(
            model_name="rca",
            name="root_cause_reviewer_comments",
            field=models.TextField(verbose_name="Reviewer comments"),
        ),
    ]
