# Generated by Django 4.1.3 on 2023-02-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("riskreg", "0007_alter_rca_contributory_cause_1_reviewer_comments_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="riskregister",
            name="entry_type",
            field=models.CharField(
                choices=[
                    ("rd_entry", "Risk library entry"),
                    ("custom_rr", "Custom risk response"),
                    ("custom_r_rr", "Custom risk, risk response"),
                    ("custom_o_r_rr", "Custom objective, risk and risk response"),
                    ("custom_c_o_r_rr", "Custom entry"),
                ],
                max_length=256,
            ),
        ),
        migrations.AlterField(
            model_name="riskregister",
            name="response_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", ""),
                    ("Off-the-shelf software", "Off-the-shelf software"),
                    ("In-house software", "In house software"),
                    ("Certificates", "Certificates"),
                    ("Documented policy", "Documented policy"),
                    ("Documented procedure", "Documented procedure"),
                    ("Other", "Other"),
                ],
                max_length=256,
                null=True,
            ),
        ),
    ]
