# Generated by Django 4.1.3 on 2023-03-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("riskreg", "0008_alter_riskregister_entry_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rca",
            name="root_cause_reviewer_comments",
            field=models.TextField(null=True, verbose_name="Reviewer comments"),
        ),
    ]
