# Generated by Django 4.1.3 on 2023-03-01 23:05

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ("riskreg", "0011_nonquillpost_quillpost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nonquillpost",
            name="content",
            field=django_quill.fields.QuillField(),
        ),
    ]
