# Generated by Django 4.1.3 on 2023-03-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("riskreg", "0012_alter_nonquillpost_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="quillpost",
            name="text",
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
