# Generated by Django 4.1.3 on 2023-03-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("riskreg", "0013_quillpost_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="nonquillpost",
            name="text",
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
