# Generated by Django 4.1.3 on 2023-03-02 12:09

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ("riskreg", "0014_nonquillpost_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rca",
            name="identified_deficiency",
            field=django_quill.fields.QuillField(),
        ),
    ]
