# Generated by Django 4.1.3 on 2023-03-02 12:25

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ("riskreg", "0015_alter_rca_identified_deficiency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rca",
            name="identified_deficiency",
            field=django_quill.fields.QuillField(verbose_name="Identified deficiency"),
        ),
        migrations.AlterField(
            model_name="rca",
            name="immediate_cause",
            field=django_quill.fields.QuillField(verbose_name="Immediate cause"),
        ),
    ]
