# Generated by Django 4.1.3 on 2023-03-03 16:12

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ("riskreg", "0018_alter_rca_contributory_cause_1_reviewer_comments_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rca",
            name="is_pervasive_comments",
            field=django_quill.fields.QuillField(verbose_name="Comments"),
        ),
        migrations.AlterField(
            model_name="rca",
            name="is_severe_comments",
            field=django_quill.fields.QuillField(verbose_name="Comments"),
        ),
        migrations.AlterField(
            model_name="rca",
            name="new_risk_response",
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name="rca",
            name="old_risk_response",
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name="rca",
            name="proposed_remedial_action",
            field=django_quill.fields.QuillField(
                verbose_name="Proposed remedial action"
            ),
        ),
        migrations.AlterField(
            model_name="rca",
            name="proposed_remedial_action_reviewer_comments",
            field=django_quill.fields.QuillField(
                blank=True, null=True, verbose_name="Reviewer comments"
            ),
        ),
        migrations.AlterField(
            model_name="rca",
            name="remedial_action_change",
            field=django_quill.fields.QuillField(
                verbose_name="What has changed as a result of the remedial action?"
            ),
        ),
        migrations.AlterField(
            model_name="rca",
            name="remedial_action_conclusion",
            field=django_quill.fields.QuillField(
                verbose_name="Remedial action conclusion"
            ),
        ),
        migrations.AlterField(
            model_name="rca",
            name="root_cause",
            field=django_quill.fields.QuillField(verbose_name="Root cause"),
        ),
        migrations.AlterField(
            model_name="rca",
            name="root_cause_reviewer_comments",
            field=django_quill.fields.QuillField(
                blank=True, null=True, verbose_name="Reviewer comments"
            ),
        ),
    ]
