# Generated by Django 4.1.3 on 2023-03-05 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("riskreg", "0019_alter_rca_is_pervasive_comments_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rca", name="new_risk_response", field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="rca", name="old_risk_response", field=models.TextField(),
        ),
    ]
