# Generated by Django 4.1.3 on 2022-12-02 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0013_alter_userattributes_user_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="Model_01_QualityObjectiveCategory",
            fields=[
                ("quality_objective_category", models.CharField(max_length=150)),
                (
                    "quality_objective_category_id",
                    models.CharField(
                        max_length=50, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "firm_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.firm"
                    ),
                ),
            ],
            options={"unique_together": {("firm_name", "quality_objective_category")},},
        ),
    ]
