# Generated by Django 4.1.3 on 2022-12-02 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_alter_userattributes_user_role"),
        ("riskregister", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RiskRegister_01_QualityObjectiveCategory",
            fields=[
                (
                    "quality_objective_category_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("quality_objective_category", models.CharField(max_length=150)),
                (
                    "firm_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.firm"
                    ),
                ),
            ],
            options={"unique_together": {("firm_name", "quality_objective_category")},},
        ),
        migrations.DeleteModel(name="Model_01_QualityObjectiveCategory",),
    ]
