# Generated by Django 4.1.3 on 2022-12-03 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_alter_userattributes_user_role"),
        ("riskregister", "0002_riskregister_01_qualityobjectivecategory_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="riskregister_01_qualityobjectivecategory",
            name="firm_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="objective_categories",
                to="accounts.firm",
            ),
        ),
        migrations.CreateModel(
            name="RiskRegister_02_QualityObjective",
            fields=[
                (
                    "quality_objective_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("quality_objective", models.CharField(max_length=5000)),
                (
                    "quality_objective_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="objectives",
                        to="riskregister.riskregister_01_qualityobjectivecategory",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("quality_objective_category", "quality_objective")
                },
            },
        ),
    ]
