# Generated by Django 4.1.3 on 2022-12-21 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_alter_userattributes_user_role"),
        (
            "riskregister",
            "0003_alter_riskregister_01_qualityobjectivecategory_firm_name_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="RiskRegister_03_QualityRisk",
            fields=[
                (
                    "quality_risk_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("quality_risk", models.CharField(max_length=5000)),
                (
                    "quality_risk_firm_size",
                    models.CharField(
                        choices=[
                            ("Small", "Small"),
                            ("Large", "Large"),
                            ("All", "All"),
                        ],
                        max_length=256,
                    ),
                ),
                (
                    "firm_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.firm"
                    ),
                ),
                (
                    "quality_objective",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risks",
                        to="riskregister.riskregister_02_qualityobjective",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RiskRegister_04_RiskResponse",
            fields=[
                (
                    "risk_response_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("risk_response", models.CharField(max_length=10000)),
                ("owner", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "response_mandatory",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")], max_length=256
                    ),
                ),
                (
                    "risk_response_firm_size",
                    models.CharField(
                        choices=[
                            ("Small", "Small"),
                            ("Large", "Large"),
                            ("All", "All"),
                        ],
                        max_length=256,
                    ),
                ),
                (
                    "response_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", ""),
                            ("Off-the-shelf software", "Off-the-shelf software"),
                            ("In-house software", "In-house software"),
                            ("Certificates", "Certificates"),
                            ("Documented policy", "Documented policy"),
                            ("Documented procedure", "Documented procedure"),
                            ("Other", "Other"),
                        ],
                        max_length=256,
                        null=True,
                    ),
                ),
                (
                    "risk_response_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Risk library", "Risk library"),
                            ("Custom entry", "Custom entry"),
                            (
                                "Custom objective, risks and response",
                                "Custom objective, risks and response",
                            ),
                            ("Custom risks and response", "Custom risks and response"),
                            ("Custom response", "Custom response"),
                        ],
                        default="risk_library",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "response_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", ""),
                            ("In place", "In place"),
                            ("in_progress", "In progress"),
                            ("not_started", "Not started"),
                        ],
                        max_length=150,
                        null=True,
                    ),
                ),
                ("comments", models.TextField(blank=True, null=True)),
                (
                    "frequency_of_review",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", ""),
                            ("Weekly", "Weekly"),
                            ("Monthly", "Monthly"),
                            ("Quarterly", "Quarterly"),
                            ("Annually", "Annually"),
                        ],
                        max_length=256,
                        null=True,
                    ),
                ),
                ("created_by", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "sign_off_owner",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "sign_off_reviewer",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("rd_entry", "rd_entry"),
                            ("custom_rr", "custom_rr"),
                            ("custom_r_rr", "custom_r_rr"),
                            ("custom_o_r_rr", "custom_o_r_rr"),
                            ("custom_c_o_r_rr", "custom_c_o_r_rr"),
                        ],
                        max_length=256,
                    ),
                ),
                (
                    "firm_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.firm"
                    ),
                ),
                (
                    "quality_risk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_responses",
                        to="riskregister.riskregister_03_qualityrisk",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RCA",
            fields=[
                (
                    "identified_deficiency_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("identified_deficiency", models.TextField()),
                ("immediate_cause", models.TextField()),
                (
                    "immediate_cause_reviewer_comments",
                    models.TextField(blank=True, null=True),
                ),
                ("contributory_cause_1", models.TextField()),
                (
                    "contributory_cause_1_reviewer_comments",
                    models.TextField(blank=True, null=True),
                ),
                ("contributory_cause_2", models.TextField(blank=True, null=True)),
                (
                    "contributory_cause_2_reviewer_comments",
                    models.TextField(blank=True, null=True),
                ),
                ("contributory_cause_3", models.TextField(blank=True, null=True)),
                (
                    "contributory_cause_3_reviewer_comments",
                    models.TextField(blank=True, null=True),
                ),
                ("root_cause", models.TextField()),
                ("root_cause_reviewer_comments", models.TextField()),
                ("proposed_remedial_action", models.TextField()),
                (
                    "proposed_remedial_action_reviewer_comments",
                    models.TextField(blank=True, null=True),
                ),
                ("preparer_signature", models.CharField(max_length=1000)),
                ("preparer_signature_date", models.DateField(auto_now=True)),
                (
                    "quality_management_head_signature",
                    models.CharField(max_length=1000),
                ),
                (
                    "quality_management_head_signature_date",
                    models.DateField(auto_now=True),
                ),
                (
                    "firm_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.firm"
                    ),
                ),
                (
                    "risk_response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="root_cause_analysis",
                        to="riskregister.riskregister_04_riskresponse",
                    ),
                ),
            ],
        ),
    ]
