# Generated by Django 4.1.3 on 2022-12-22 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_alter_userattributes_user_role"),
        ("riskregister", "0005_remove_riskregister_03_qualityrisk_firm_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="riskregister_04_riskresponse",
            name="firm_name",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.firm",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="riskregister_04_riskresponse",
            name="rd_risk_response_id",
            field=models.IntegerField(default=0),
        ),
    ]
