# Generated by Django 4.1.3 on 2023-01-10 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_alter_userattributes_user_role"),
        ("riskregister", "0006_riskregister_04_riskresponse_firm_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="rca", name="risk_response",),
        migrations.CreateModel(
            name="RiskRegister",
            fields=[
                ("entry_id", models.AutoField(primary_key=True, serialize=False)),
                ("quality_objective_category", models.CharField(max_length=150)),
                ("quality_objective", models.CharField(max_length=5000)),
                ("quality_risk", models.CharField(max_length=5000)),
                (
                    "quality_risk_firm_size",
                    models.CharField(
                        choices=[
                            ("Small", "Small"),
                            ("Large", "Large"),
                            ("All", "All"),
                        ],
                        max_length=256,
                    ),
                ),
                ("risk_response", models.CharField(max_length=10000)),
                ("owner", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "response_mandatory",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")], max_length=256
                    ),
                ),
                (
                    "risk_response_firm_size",
                    models.CharField(
                        choices=[
                            ("Small", "Small"),
                            ("Large", "Large"),
                            ("All", "All"),
                        ],
                        max_length=256,
                    ),
                ),
                (
                    "response_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", ""),
                            ("Off-the-shelf software", "Off-the-shelf software"),
                            ("In-house software", "In-house software"),
                            ("Certificates", "Certificates"),
                            ("Documented policy", "Documented policy"),
                            ("Documented procedure", "Documented procedure"),
                            ("Other", "Other"),
                        ],
                        max_length=256,
                        null=True,
                    ),
                ),
                (
                    "risk_response_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Risk library", "Risk library"),
                            ("Custom entry", "Custom entry"),
                            (
                                "Custom objective, risks and response",
                                "Custom objective, risks and response",
                            ),
                            ("Custom risks and response", "Custom risks and response"),
                            ("Custom response", "Custom response"),
                        ],
                        default="risk_library",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "response_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", ""),
                            ("In place", "In place"),
                            ("in_progress", "In progress"),
                            ("not_started", "Not started"),
                        ],
                        max_length=150,
                        null=True,
                    ),
                ),
                ("comments", models.TextField(blank=True, null=True)),
                (
                    "frequency_of_review",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", ""),
                            ("Weekly", "Weekly"),
                            ("Monthly", "Monthly"),
                            ("Quarterly", "Quarterly"),
                            ("Annually", "Annually"),
                        ],
                        max_length=256,
                        null=True,
                    ),
                ),
                ("created_by", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "sign_off_owner",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "sign_off_reviewer",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("rd_entry", "rd_entry"),
                            ("custom_rr", "custom_rr"),
                            ("custom_r_rr", "custom_r_rr"),
                            ("custom_o_r_rr", "custom_o_r_rr"),
                            ("custom_c_o_r_rr", "custom_c_o_r_rr"),
                        ],
                        max_length=256,
                    ),
                ),
                ("rd_risk_response_id", models.IntegerField(default=0)),
                (
                    "firm_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_register_Entry",
                        to="accounts.firm",
                    ),
                ),
            ],
            options={"unique_together": {("firm_name", "quality_objective_category")},},
        ),
        migrations.AddField(
            model_name="rca",
            name="entry",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="root_cause_analysis",
                to="riskregister.riskregister",
            ),
            preserve_default=False,
        ),
    ]
