# Generated by Django 4.1.3 on 2022-12-19 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RiskDatabase_01_QualityObjectiveCategory",
            fields=[
                (
                    "quality_objective_category_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("quality_objective_category", models.CharField(max_length=150)),
            ],
            options={"ordering": ["quality_objective_category"],},
        ),
        migrations.CreateModel(
            name="RiskDatabase_02_QualityObjective",
            fields=[
                (
                    "quality_objective_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("quality_objective", models.CharField(max_length=5000)),
                ("quality_objective_ref", models.CharField(max_length=120)),
                (
                    "quality_objective_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="objectives",
                        to="riskdatabase.riskdatabase_01_qualityobjectivecategory",
                    ),
                ),
            ],
            options={"ordering": ["quality_objective_category", "quality_objective"],},
        ),
        migrations.CreateModel(
            name="RiskDatabase_03_QualityRisk",
            fields=[
                (
                    "quality_risk_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("quality_risk", models.CharField(max_length=5000)),
                ("quality_risk_ref", models.CharField(max_length=150)),
                (
                    "quality_risk_firm_size",
                    models.CharField(
                        choices=[
                            ("Small", "Small"),
                            ("Large", "Large"),
                            ("All", "All"),
                        ],
                        max_length=256,
                    ),
                ),
                (
                    "quality_objective",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risks",
                        to="riskdatabase.riskdatabase_02_qualityobjective",
                    ),
                ),
            ],
            options={"ordering": ["quality_objective", "quality_risk"],},
        ),
        migrations.CreateModel(
            name="RiskDatabase_04_RiskResponse",
            fields=[
                (
                    "risk_response_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("risk_response", models.CharField(max_length=10000)),
                ("risk_response_ref", models.CharField(max_length=150)),
                (
                    "response_mandatory",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")], max_length=256
                    ),
                ),
                (
                    "risk_response_firm_size",
                    models.CharField(
                        choices=[
                            ("Small", "Small"),
                            ("Large", "Large"),
                            ("All", "All"),
                        ],
                        max_length=256,
                    ),
                ),
                (
                    "quality_risk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_response",
                        to="riskdatabase.riskdatabase_03_qualityrisk",
                    ),
                ),
            ],
            options={"ordering": ["quality_risk", "risk_response"],},
        ),
    ]
